### ISSUE TITLE
https://coderunner.baejino.com/ 접속시 502 에러 발생

### ISSUE THREAD

**Issue by partrita** [baealex/coding-doumi#1]
Error 502 Ray ID: 580c44b839fbe7ed • 2020-04-08 13:17:25 UTC
Bad gateway

**Comment by baealex** [comment]
이 이슈를 보고 [https://coding.doum.app](https://coding.doum.app)에서 다시 열었습니다. 조금씩 개선해 나가도록 하겠습니다. 관심 가져주셔서 진심으로 감사합니다 😁
